#include "exti.h"

void EXTI_Init(void){
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;
	SYSCFG->EXTICR[2]|=(SYSCFG_EXTICR3_EXTI11_PA|SYSCFG_EXTICR3_EXTI8_PB|SYSCFG_EXTICR3_EXTI9_PB);
	SYSCFG->EXTICR[3]|=SYSCFG_EXTICR4_EXTI12_PA;
	//EXTI->RTSR|=(EXTI_RTSR_RT11|EXTI_RTSR_RT12|EXTI_RTSR_RT8|EXTI_RTSR_RT9);
	EXTI->FTSR|=(EXTI_FTSR_FT11|EXTI_FTSR_FT12|EXTI_FTSR_FT8|EXTI_FTSR_FT9);
	EXTI->IMR|=(EXTI_IMR_IM11|EXTI_IMR_IM12|EXTI_IMR_IM8|EXTI_IMR_IM9);
	NVIC_EnableIRQ(EXTI4_15_IRQn);
}

void EXTI4_15_IRQHandler(void){
	EXTI->PR|=(EXTI_PR_PIF11|EXTI_PR_PIF12|EXTI_PR_PIF8|EXTI_PR_PIF9);
}
