#include "spi.h"
//#define SPI2_DMA

extern uint8_t ccbuf[];

void SPI1_Init(void){
  RCC->APB2ENR |= RCC_APB2ENR_SPI1EN;
	GPIOA->MODER&=~(GPIO_MODER_MODER5|GPIO_MODER_MODER6|GPIO_MODER_MODER7); // SPI1: SCK, MISO, MOSI
	GPIOA->MODER|=(GPIO_MODER_MODER5_1|GPIO_MODER_MODER6_1|GPIO_MODER_MODER7_1);
	GPIOA->OSPEEDR|=(GPIO_OSPEEDER_OSPEEDR5|GPIO_OSPEEDER_OSPEEDR6|GPIO_OSPEEDER_OSPEEDR7);
	GPIOA->AFR[0]&=~(GPIO_AFRL_AFRL5|GPIO_AFRL_AFRL6|GPIO_AFRL_AFRL7);
	GPIOA->AFR[0]|=((0b0000<<GPIO_AFRL_AFRL5_Pos)|(0b0000<<GPIO_AFRL_AFRL6_Pos)|(0b0000<<GPIO_AFRL_AFRL7_Pos));
	
	RCC->AHBENR|=RCC_AHBENR_DMAEN;
	SPI1->CR2|=(SPI_CR2_TXDMAEN|SPI_CR2_RXDMAEN|SPI_CR2_FRXTH);
	
	SPI1->CR1=0;
  SPI1->CR1|=(SPI_CR1_SSM | SPI_CR1_SSI | SPI_CR1_MSTR | (0b111<<SPI_CR1_BR_Pos)); // SPI_CR1_SPE | 
	SPI1->CR1|=SPI_CR1_SPE;
}

void SPI2_Init(void){
	
	RCC->APB1ENR|=RCC_APB1ENR_SPI2EN;
	GPIOB->MODER&=~(GPIO_MODER_MODER13|GPIO_MODER_MODER15);
	GPIOB->MODER|=(GPIO_MODER_MODER13_1|GPIO_MODER_MODER15_1);
	GPIOB->OSPEEDR|=(GPIO_OSPEEDER_OSPEEDR13|GPIO_OSPEEDER_OSPEEDR15);
	GPIOB->AFR[1]|=0x00000000;
	SPI2->CR1=0;
	SPI2->CR1|=(SPI_CR1_BIDIMODE|SPI_CR1_BIDIOE|(0b000<<SPI_CR1_BR_Pos)|SPI_CR1_MSTR|SPI_CR1_SSM|SPI_CR1_SSI); //
	
	MODIFY_REG(SPI2->CR2, (0b1111<<SPI_CR2_DS_Pos), (0b1000<<SPI_CR2_DS_Pos));
	
	#ifdef SPI2_DMA
	RCC->AHBENR|=RCC_AHBENR_DMAEN;
	SPI2->CR2|=SPI_CR2_TXDMAEN;
	/*DMA_CSELR->CSELR|=(0b0001<<DMA_CSELR_C3S_Pos);*/
	DMA1_Channel5->CCR|=(DMA_CCR_MINC|DMA_CCR_DIR|DMA_CCR_PSIZE_0|DMA_CCR_MSIZE_0); //
	DMA1_Channel5->CPAR=(uint32_t)(&(SPI2->DR));
	#endif // SPI_DMA
	
	SPI2->CR1|=SPI_CR1_SPE;
}

uint16_t b9;

void SPI2_Send_Byte(uint8_t op, uint8_t b){
	#ifdef SPI2_DMA
	b9=((op<<8)|b);
	DMA1_Channel5->CCR&=~DMA_CCR_EN;
	DMA1_Channel5->CMAR=(uint32_t)&b9;
	DMA1_Channel5->CNDTR=1;
	DMA1_Channel5->CCR|=DMA_CCR_EN;
	while((SPI2->SR&SPI_SR_BSY));
	//for(uint32_t i=0; i<650; ++i);
	#else
	SPI2->DR = ((op<<8)|b);
	while(!(SPI2->SR&SPI_SR_TXE));
	#endif // SPI_DMA
}
